const error = {
  500: "OK",
  501: "#ERR->USER_NOT_AUTHORISED",
  502: "#ERR->PROJECT_NOT_VALID",
  503: "#ERR->USER_PROJECT_NOT_COMPATIBLE",
  504: "#ERR->SENDER_RECEIVER_NOT_COMPATIBLE",
  505: "#ERR->DEVICE_OFFLINE",
  506: "#ERR->PROJECT_OFFLINE"
};

module.exports = error;
